### ISSUE TITLE
No graceful shutdown due to infinite connect routine

### ISSUE THREAD

**Issue by DominiqueFuchs** [Atem18/kraky#158]
Hi there,

I just stumbled across a minor annoyance and thought I'd give it a try to see what you think about this:

As I see it, there is no _clean_ way of shutting down a kraky task gracefully, in terms of closing the connection(s) and finishing the asyncio Task without any warnings or exceptions. Rather contrary, I just burned quite a bit of time (more than I'm happy to admit) until figuring out why my unit tests where failing on some occasions with seemingly misplaced asyncio errors regarding unreferenced tasks:

While using the library, I automatically/intuitively assumed that awaiting the [_disconnect_](https://github.com/Atem18/kraky/blob/e4aa82ea4002b3928d751de495e51d57eea83ec3/kraky/ws.py#L125C14-L125C14) coroutine will make the Task containing the _connect_ coroutine finish (as in: the connection is closed, thus the connect coroutine returns). Only later when looking into the corresponding code sections I realised that the connect coroutine runs an [infinite while loop](https://github.com/Atem18/kraky/blob/e4aa82ea4002b3928d751de495e51d57eea83ec3/kraky/ws.py#L62C1-L62C20) and none of the except blocks handles the case of an intentional shutdown. Thus, the only remaining ways are hard cancellations of the Tasks and/or of the event_loop, both options are not considered 'clean', triggering warnings and/or exceptions on shutdown.

Handling that case (intentional shutdown, thus triggering the connect coroutine to return) would be rather trivial, but there may be different approaches with different implications, I'd be happy to get your opinion if and how you'd want this to be handled:

1) calling _dis_connect on all connections should automatically exit the connect main routine. I'd regard this as logical/intuitive, but this could be considered as breaking or at least significant behavioural change, thus unfavored. Also, it may be intentional to keep the coroutines connect loop alive even after all connections have been disconnected because the user may just do some resting and reconnect later without creating a new instance. Otherwise I'd think about something simple as changing the `while True:` to something like `while self.connections:`

2) Introducing an additional function like `self.shutdown` that triggers the connect routine to break free – simplest option may be just setting a boolean member attribute and changing  the `while True:` condition in the connect coroutine to `while self.connections and not self.shutdown:`. In this case it should be considered if the shutdown function should automatically call close on all active connections or if this should be the responsibility of the user.

**Comment by Atem18** [comment]
@DominiqueFuchs Thanks a lot for the report.

I would say that changing from `while True:` to `while self.connections:` is the simplest.

We can see later if a bigger change is needed.

Can you make a pull request and test it ?

Thanks a lot in advance.

**Comment by Atem18** [comment]
@DominiqueFuchs Release 2023.08.16 is now available. Thanks again for your contribution !

**Comment by DominiqueFuchs** [comment]
Cool! 🙏🏻

Thanks to you for building and maintaining this library! As its already been really useful for me as a go-to lib within some personal project I'm happy to contribute back here. I'll take a look if I can provide some test additions to the workflow. 🧪

**Comment by Atem18** [comment]
I am glad if it's useful for you.

I've wanted to add new functions from Kraken API but lacked the time.

But since now I have Github Copilot, it's trivial to add code based on documentation so expect new releases soon !
