### ISSUE TITLE
Any idea why my web sockets order will not send?

### ISSUE THREAD

**Issue by kettlewarrior** [Atem18/kraky#53]
Hi,

I am trying to use the web sockets client to send an order, though it doesn't seem to get sent. The connection works for private topics, e.g. openorders subscription, however not for sending an order:

I am fairly new to Python (but not to coding) - so really sorry if I've missed something glaring - but have tried:

```kraky_private_ws_client = KrakyWsClient("production-auth")```

```await kraky_private_ws_client.add_order(token=ws_token,pair="<some_pair>",type="sell",ordertype="limit",price=10.0,volume=1.75,validate="true")```

and also

    ```ordSub=asyncio.create_task(kraky_private_ws_client.add_order(token=ws_token,pair="<some_pair>",type="sell",ordertype="limit",price=10.0,volume=1.75,validate="true"))
    await ordSub```

- I can add debug output to add_order, which is triggered pre the call to _send (.e.g print out the params), but never post (e.g. print ("returned from _send"))

- I can add debug output to _send , which is never triggered at all (.e.g some string saying _send ran), e.g.:
   ```async def _send(self, data: dict, connection_name: str = "main") -> None:
        print ("running send...")```

Running  under:

```Python 3.8.10 (default, Sep 28 2021, 16:10:42) ```

Thanks in advance for the help!

**Comment by Atem18** [comment]
Hi,

I don't know which kind of errors you have but I did a test on my side.

I discovered an issue in my functions but only when you execute the functions which does not seems to be your case.

Please update to the latest version (2021.11.04) and test the following code:

```python
import asyncio

from kraky import KrakyApiClient, KrakyWsClient


async def handle_ws(message):
    print(message)


async def main():
    kraken_api_key = ""
    kraken_secret = ""
    kraky_api_client = KrakyApiClient(api_key=kraken_api_key, secret=kraken_secret)
    kraky_ws_client = KrakyWsClient(connection_env="production-auth")
    asyncio.create_task(kraky_ws_client.connect(handler=handle_ws))
    ws_token = await kraky_api_client.get_web_sockets_token()
    await kraky_ws_client.subscribe(
        subscription={
            "token": ws_token,
            "name": "openOrders",
        },
    )
    await kraky_ws_client.add_order(
        token=ws_token,
        pair="XBT/USD",
        type="sell",
        ordertype="limit",
        price="10.0",
        volume="1.75",
        validate="true",
    )


loop = asyncio.get_event_loop()
loop.create_task(main())
loop.run_forever()
```

**Comment by kettlewarrior** [comment]
Hi,

This works now - I can see the order going out to Kraken. Thanks for your help!

With the problem I had, I did not get any exceptions - a totally silent problem. 

Thanks again (for the help, and for Kraky!)

**Comment by Atem18** [comment]
@kettlewarrior No problem, thanks for using it !
